# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MoneyWire' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MoneyWire

  # Required by RNFirebase
  pod 'Firebase/Core'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
end
